### ISSUE TITLE
Final Tracking Files Appear to be Empty

### ISSUE THREAD

**Issue by smeisler** [scilus/tractoflow#20]
Hello,

I ran Tractoflow on multiple subjects and the process completed with no errors according to the outfile produced by sbatch. I tried to import the .trk files into Trackvis, which said there were no fibers to be tracked. This was reaffirmed when I imported the .trk files into Vistasoft with 'read_trk_to_fg'. 

I am confused by this output, since the images produced in the later processing stages all look correct. For example, I have attached below a screenshot from FSLView showing the V1 vector image modulated by the FA image (both in the results/DTI_Metrics folder). Do you know why this might be?

To provide a little more information, I am running Tractoflow on a Linux HPC system through the most recent Singularity container. The subjects did not have a reverse B0 image. The final tracking files are about 1 kb each. I'll be happy to provide more information or pictures as needed.

Thanks,
Steven

![image](https://user-images.githubusercontent.com/27028726/79627542-41634380-8107-11ea-95b1-774aeb0f11e2.png)

**Comment by smeisler** [comment]
I might have figured out the problem. I noticed that the FRF folder was empty. We only scanned at B=0 and B=700. I set the DTI shell at "0 700" and the fODF shell at "700". Since fODF usually requires higher b-values, do you think this part of the pipeline was ignored?

**Comment by mdesco** [comment]
You probably need “0 700” for the fODF as well. The FRF needs the b0 image for a proper FRF estimation.

@guillaume, do you confirm?
@guillaume, we might want to send a warning out if this happens…

Max

On Apr 18, 2020, at 11:35, Steven Meisler <notifications@github.com<mailto:notifications@github.com>> wrote:



I might have figured out the problem. I noticed that the FRF folder was empty. We only scanned at B=0 and B=700. I set the DTI shell at "0 700" and the fODF shell at "700". Since fODF usually requires higher b-values, do you think this part of the pipeline was ignored?

**Comment by smeisler** [comment]
I am rerunning with the new fODF argument now and will update when done, thanks for the quick reply!

**Comment by smeisler** [comment]
That did the trick, thank you
